Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,7 +3,8 @@ name: Push to GitLab
 on:
   push:
     branches:
-      - master 
+      - master  # Trigger the workflow on the 'master' branch
+
 jobs:
   push_to_gitlab:
     runs-on: ubuntu-latest
@@ -25,9 +26,9 @@ jobs:
       run: |
         git fetch gitlab main  # Fetch the latest changes from the GitLab 'main' branch
 
-    - name: Merge GitLab main branch into GitHub master
+    - name: Attempt to merge GitLab main branch into GitHub master
       run: |
-        git merge gitlab/main --allow-unrelated-histories  # Merge the remote 'main' branch into the 'master' branch
+        git merge gitlab/main --allow-unrelated-histories || exit 0  # If merge fails, exit with status 0
 
     - name: Push code to GitLab
       run: |
